# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a96e617f21da8df3097b65072283d2c634249428ff9981c0014f1b143a601cd6c670c89ae7131e752f9c4d1e21a3caa8ea687f114a09ff7594403cc67cf012f

test:
  secret_key_base: 631b70547dcd80518ae5cff41938ebb8288ee063a0065eef6c2387a81db1f6383ff7fd36f0c83a4e7425b8092fd4aa3243e56c07af9acff00cc82252470173d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
